services:
  - type: web
    name: laravel-api
    env: php
    plan: free
    buildCommand: 'composer install'
    startCommand: 'php artisan migrate && php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
